Blast4-archive ::= {
  request {
    body get-request-info {
      request-id "Error"
    }
  },
  results {
  },
  messages {
    {
      code 2,
      message "Command line argument error: Argument ""query"". File is not
 accessible: `dddddd.in'"
    }
  }
}
